#
# Makefile for cross-compiler version of CC65.
# (Modified for use on *nix machines -Intruder  1993)
#
# modified : 16.06.96 B.Schick

CC=gcc
CFLAGS = #-O -O1 -O2 -O3 -fomit-frame-pointer -m486
LDFLAGS= #-s
BINDIR = ../bin
CP = cp 
RM = rm -f

C_SRCS = error.c expr1.c expr2.c expr3.c function.c glb.c \
	globlvar.c io.c lexer.c main.c optab1.c optab2.c optimize.c \
	preproc.c rwords.c stmt1.c stmt2.c symtab.c path.c copyleft.c

H_SRCS = cc65.h cclex.h

OBJS =  error.o expr1.o expr2.o expr3.o function.o glb.o globlvar.o \
	io.o lexer.o main.o optab1.o optab2.o optimize.o preproc.o rwords.o \
	stmt1.o stmt2.o symtab.o path.o copyleft.o

XOBJS = cruft.o

EXECS = cc65.exe xopt.exe cc42.exe

all : $(EXECS)

cc65.exe : $(OBJS) $(XOBJS) code-65.o
	$(CC) $(LDFLAGS) -o cc65 $(OBJS) $(XOBJS) code-65.o

cc42.exe : $(OBJ) $(XOBJS) code-42.o
	$(CC) $(LDFLAGS) -o cc42 $(OBJS) $(XOBJS) code-42.o

$(OBJS) : $(H_SRCS)

$(XOBJS) : $(H_SRCS)

xopt.exe : xopt.c
	$(CC) $(CFLAGS) -o xopt xopt.c

install : $(EXECS)
	$(CP) $(EXECS) $(BINDIR)

clean : 
	$(RM) *.o *~ core $(EXECS) compile.err errlist

